[package]
name = "splitter"
version = "0.1.0"
authors = ["Isaac Azuelos <isaac@azuelos.ca>"]

[dependencies]
calamine = "0.14.6"
csv = "1.0.1"
# clap = "2.32.0"

url = "1.7.1"

gtk = "0.5.0"
gio = "0.5.0"
gdk = "0.9.0"
